src/competences/urls.py
from django.urls import path

from competences import views
from eval_django.utils import spath

app_name = "competences"

urlpatterns = [
    path('',views.index,name='index'),
    path('accepter/<int:req_id>', views.accepter,name="accepter"),
    path('profil/<int:uid>', views.profil_autre, name="profil_autre"),

    spath('login', views.LoginV.as_view()),
    spath('logout', views.logout_view),
    spath('competences', views.competences),
    spath('profil', views.profil),
    spath('requete', views.requete)

]

src/eval_django/urls.py
from django.contrib import admin
from django.urls import path, include

import competences

urlpatterns = [
    path('admin/', admin.site.urls),
    path('competences/', include('competences.urls','competences')),

]

src/competences/models.py
from __future__ import annotations

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model, QuerySet


# Create your models here.

class Competence(Model):
    nom = models.CharField(max_length=256)

    def __str__(self):
        return self.nom

    class Meta:
        pass


class UserProfile(Model):
    user = models.ForeignKey(to=User, primary_key=True, on_delete=models.CASCADE)
    competences = models.ManyToManyField(to=Competence, default=[])

    def get_requetes(self, competences: set[Competence]) -> QuerySet[Requete]:
        return Requete.objects.filter(owner=self, competence__in=competences)

    @classmethod
    def get_for_user(cls, user: User) -> UserProfile:
        try:
            return cls.objects.get(pk=user.id)
        except UserProfile.DoesNotExist:
            return cls.objects.create(user=user)


class Requete(Model):
    description = models.CharField(max_length=256)
    date = models.DateField()
    competence = models.ForeignKey(to=Competence, on_delete=models.CASCADE)
    owner = models.ForeignKey(to=UserProfile, on_delete=models.CASCADE)
    assigned = models.ForeignKey(to=UserProfile, on_delete=models.CASCADE, related_name="assigned", blank=True,
                                 null=True)

    def __str__(self):
        return self.description + ": " + str(self.competence) + ", le " + str(self.date)

src/competences/forms.py
from django import forms
from django.db.models import QuerySet

from competences.models import Competence, Requete
from eval_django.utils import try_or


# Pas de models forms car propriété owner requise (?)
class RequeteForm(forms.Form):
    description = forms.CharField()
    date = forms.DateField(widget=forms.SelectDateWidget())
    competence = forms.ModelChoiceField(label="Compétence :",
                                        queryset=try_or(lambda: Competence.objects.all(), Competence.objects.none()),
                                        widget=forms.Select(attrs={"class": "form"}))


class ConfirmForm(forms.Form):
    pass


class CompetencesForm(forms.Form):
    #bar = forms.CharField()
    #foo = forms.TypedMultipleChoiceField(choices=[(0,"A"),(1,"B")])
    comps = forms.ModelMultipleChoiceField(label="Compétences (ctr click pour en sélectionner plusieurs)",
                                           queryset=try_or(lambda: Competence.objects.all(), Competence.objects.none()),
                                           widget=forms.SelectMultiple(attrs={"class": ""}))

src/competences/views.py
import datetime

from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.core.exceptions import BadRequest
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from competences.forms import CompetencesForm, ConfirmForm, RequeteForm
from competences.models import UserProfile, Requete, Competence


# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return render(request, "competences/index.html", {"competences" : Competence.objects.all(),"requetes_recentes" : Requete.objects.filter(assigned=None, date__gte=datetime.date.today())[:5].all()})
    usr = UserProfile.get_for_user(request.user)

    requetes_self = Requete.objects.filter(owner=usr, date__gte=datetime.date.today()).order_by("date")
    requetes_disponibles = Requete.objects.exclude(owner=usr).filter(competence__in=usr.competences.all(),
                                                                     assigned=None,
                                                                     date__gte=datetime.date.today()).order_by("date")
    requetes_acceptes = Requete.objects.filter(assigned=usr,
                                               date__gte=datetime.date.today()).order_by("date")
    return render(request, "competences/index.html",
                  {
                      "requetes_self": requetes_self,
                      "requetes_disponibles": requetes_disponibles,
                      "requetes_acceptes": requetes_acceptes
                  })


class LoginV(LoginView):
    template_name = "competences/login.html"
    next_page = "/competences/"


def profil_autre(request, uid: int):
    if not request.user.is_authenticated:
        raise PermissionError()

    user = get_object_or_404(User, pk=uid)

    return render(request, "competences/profil_autre.html", {"prof": UserProfile.get_for_user(user),
                                                             "competences": UserProfile.get_for_user(
                                                                 user).competences.all()})


def profil(request):
    if not request.user.is_authenticated:
        raise PermissionError()

    return render(request, "competences/profil.html",
                  {"competences": UserProfile.get_for_user(request.user).competences.all(),
                   "profil": UserProfile.get_for_user(request.user)})


def accepter(request, req_id: int):
    if not request.user.is_authenticated:
        raise PermissionError()
    if request.method == "POST":
        form = ConfirmForm(request.POST)

        if form.is_valid():
            prof = UserProfile.get_for_user(request.user)
            req = Requete.objects.get(pk=req_id)
            if req.date >= datetime.date.today() and req.assigned is None and prof.competences.contains(req.competence):
                req.assigned = prof
                req.save()
                return HttpResponseRedirect("/competences")

        raise BadRequest()
    else:
        form = ConfirmForm()
        return render(request, "competences/accepter.html", {"form": form, "req_id": req_id})


def requete(request):
    if not request.user.is_authenticated:
        raise PermissionError()
    if request.method == "POST":
        form = RequeteForm(request.POST)

        if form.is_valid():
            prof = UserProfile.get_for_user(request.user)
            Requete.objects.create(description=form.cleaned_data["description"],
                                   competence=form.cleaned_data["competence"], date=form.cleaned_data["date"],
                                   owner=prof)
            return HttpResponseRedirect("/competences")

        raise BadRequest()
    else:
        form = RequeteForm()
        return render(request, "competences/requete.html", {"form": form})


def competences(request):
    if not request.user.is_authenticated:
        raise PermissionError()
    if request.method == "POST":
        form = CompetencesForm(request.POST)

        if form.is_valid():
            UserProfile.get_for_user(request.user).competences.set(form.cleaned_data["comps"])
            return HttpResponseRedirect("/competences")

        raise BadRequest()

    else:
        form = CompetencesForm()
        return render(request, "competences/competences.html", {"form": form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("competences:index"))

src/competences/templates/competences/accepter.html
{% extends "competences/main.html" %}


{% block content %}

<h1>Accepter cette requête ?</h1>


<form action="{% url 'competences:accepter' req_id=req_id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Accepter">
    <a class="btn btn-secondary" href="/competences">Refuser</a>
</form>




{% endblock %}

src/competences/templates/competences/card.html
<div class="card m-2">
        <div class="card-body">
            <h5 class="card-title">{{ title }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ subtitle }}</h6>
            <p class="card-text">
                {{ body }}
            </p>

        </div>
</div>

src/competences/templates/competences/competences.html
{% extends "competences/main.html" %}


{% block content %}

<h1>Liste des compétences</h1>


<form action="{% url 'competences:competences' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Enregistrer">
</form>




{% endblock %}

src/competences/templates/competences/index.html
{% extends "competences/main.html" %}


{% block content %}


{% if user.is_authenticated %}
<h2> Demandes pertinentes </h2>

 {% for req in requetes_disponibles %}

    <div class="card m-2" style="width: 24rem;">
        <div class="card-body">
            <h5 class="card-title">{{ req.description }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ req.date }}</h6>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ req.competence }}</h6>
            <p class="card-text">
                De <a href="{% url 'competences:profil_autre' uid=req.owner.user.id %}">{{ req.owner.user.username }}</a>
            </p>
            <a href="{% url 'competences:accepter' req_id=req.id %}" class="card-link">Accepter</a>

        </div>
    </div>


    {% endfor %}

<h2> Mes demandes <a class="btn btn-link" href="{% url 'competences:requete' %}">+ Ajouter</a></h2>

<div class="d-flex flex-row">


    {% for req in requetes_self %}

    <div class="card m-2" style="width: 24rem;">
        <div class="card-body">
            <h5 class="card-title">{{ req.description }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ req.date }}</h6>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ req.competence }}</h6>
            <p class="card-text">
                {% if req.assigned %}
                Assigné à <a href="{% url 'competences:profil_autre' uid=req.assigned.user.id %}">{{ req.assigned.user.username }} </a>


                {% endif %}
            </p>

        </div>
    </div>


    {% endfor %}

</div>


<h2>Requêtes acceptés</h2>

 {% for req in requetes_acceptes %}

    <div class="card m-2" style="width: 24rem;">
        <div class="card-body">
            <h5 class="card-title">{{ req.description }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ req.competence }}</h6>
            <p class="card-text">
                {% if req.assigned %}
                   De <a href="{% url 'competences:profil_autre' uid=req.owner.user.id %}">{{ req.owner.user.username }}</a>
                {% endif %}
            </p>

        </div>
    </div>


    {% endfor %}



{% else %}



<h2> Liste des compétences</h2>

<div class="d-flex flex-row">


    {% for c in competences %}

    <div class="card m-2" style="width: 24rem;">
        <div class="card-body">
            <h5 class="card-title">{{ c.nom }}</h5>

        </div>
    </div>


    {% endfor %}

</div>


<h2> Requêtes récentes</h2>

<div class="d-flex flex-row">


    {% for req in requetes_recentes %}

    <div class="card m-2" style="width: 24rem;">
        <div class="card-body">
            <h5 class="card-title">{{ req.description }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ req.competence }}</h6>
        </div>
    </div>

    {% endfor %}

</div>



{% endif %}

{% endblock %}

src/competences/templates/competences/login.html
{% extends "competences/main.html" %}

{% block title %}Compétences - Connexion{% endblock %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'competences:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
<input type="submit">
<input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock %}

src/competences/templates/competences/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Compétences{% endblock %}</title></head>
    <style>
        form {
            margin-left: 1em;
        }
    </style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
        <div class="container-fluid">
        <a class="navbar-brand" href="/competences">Competences</a>
        <div class="align-self-end d-flex">
            {% if user.is_authenticated %}
            <p>{{ user.get_username }} - <a href="{% url 'competences:profil' %}" class="btn btn-primary">Profil</a> - <a class="btn btn-secondary" href="/competences/logout">Déconnexion</a></p>
    {% else %}
            <a href="{% url 'competences:login' %}" class="btn btn-primary">Login</a>
    {% endif %}
        </div>
      </div>
    </nav>



<main class="m-2">
{% block content %}{% endblock %}
</main>
</body>
</html>

src/competences/templates/competences/profil.html
{% extends "competences/main.html" %}

{% block title %}Compétences - Profil{% endblock %}

{% block content %}


<div class="card m-4">
    <div class="card-body">
        <h5 class="card-title">Vos compétences</h5>
        <p class="card-text">
        <ul>
            {% for c in competences %}
                  <li><strong>{{ c.nom }}</strong></li>
            {% endfor %}
        </ul>
        </p>
        <a class="btn btn-link" href="{% url 'competences:competences'%}">Modifier vos compétences</a>
    </div>
</div>

{% endblock %}

src/competences/templates/competences/profil_autre.html
{% extends "competences/main.html" %}


{% block title %}Compétences - Profil de {{ prof.user.username }}{% endblock %}

{% block content %}



{% if user.is_authenticated %}


<div class="card m-4">
    <div class="card-body">
        <h4 class="card-title">{{ prof.user.username }}</h4>
        <p class="card-text">
            <label><strong>Nom: </strong> {{ prof.user.first_name }}</label> <br/>
            <label><strong>Prénom: </strong> {{ prof.user.last_name }}</label> <br/>
            <label><strong>Email: </strong> {{ prof.user.email }}</label> <br/>

        <br/>

        <h5>Compétences</h5>
        <ul>
            {% for c in competences %}
            <li><strong>{{ c.nom }}</strong></li>
            {% endfor %}
        </ul>
        <br/>

        </p>
    </div>
</div>

{% endif %}

{% endblock %}

src/competences/templates/competences/requete.html
{% extends "competences/main.html" %}

{% block title %}Compétences - Ajouter une requête{% endblock %}

{% block content %}

<h1>Créer une requête</h1>


<form action="{% url 'competences:requete' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Ajouter">
</form>





{% endblock %}